#pragma once
enum E_CHARACTER_TYPE
{
	E_CHARACTER_TYPE_DAO,
	E_CHARACTER_TYPE_BAZZI,

	E_CHARACTER_TYPE_END,
};
enum E_TEAM_TYPE
{
	E_TEAM_TYPE_BLUE,
	E_TEAM_TYPE_RED,
	E_TEAM_TYPE_END,
};
enum E_CHARACTER_STATE
{
	E_CHARACTER_STATE_STAND_UP, //기본
	E_CHARACTER_STATE_STAND_DOWN,
	E_CHARACTER_STATE_STAND_RIGHT,
	E_CHARACTER_STATE_STAND_LEFT,
	E_CHARACTER_STATE_DROWNING, //익사
	E_CHARACTER_STATE_REVIVE,	//부활
	E_CHARACTER_STATE_DEATH,	//죽음
	E_CHARACTER_STATE_END
};


enum E_MAP_TYPE
{
	E_MAP_TYPE_1,
	E_MAP_TYPE_2,
	E_MAP_TYPE_3,
	E_MAP_TYPE_END
};
enum E_OBJ_LIST_TYPE
{
	E_OBJ_LIST_TYPE_BLOCK,
	E_OBJ_LIST_TYPE_ITEM , 
	E_OBJ_LIST_TYPE_BUBBLE,
	E_OBJ_LIST_END
};
enum E_BLOCK_TYPE
{
	E_BLOCK_TYPE_BASIC,
	E_BLOCK_TYPE_PUSH,
	E_BLOCK_TYPE_BUSH,
	E_BLOCK_TYPE_STATIC,
	E_BLOCK_TYPE_END
};



enum E_ITEMTYPE
{
	E_ITEMTYPE_BUBBLE,
	E_ITEMTYPE_POWER,
	E_ITEMTYPE_SPEED,
	E_ITEMTYPE_MAXPOWER,
	E_ITEMTYPE_MAXSPEED,
	E_ITEMTYPE_KICK,
	E_ITEMTYPE_MINE,	//압정
	E_ITEMTYPE_BANANA,//바나나
	E_ITEMTYPE_DART,//다트
	E_ITEMTYPE_END,

};
//생산 타입
enum E_OBJECT_CREATE_TYPE
{
	E_OBJECT_CREATE_TYPE_BUBBLE,
	E_OBJECT_CREATE_TYPE_BANANA,
	E_OBJECT_CREATE_TYPE_MINE,
	E_OBJECT_CREATE_TYPE_DART,
	E_OBJECT_CREATE_TYPE_END,
};

enum E_GAME_STATE
{
	E_GAME_STATE_RPOGRESS,//진행중
	E_GAME_STATE_BLUE_WIN,
	E_GAME_STATE_RED_WIN,
	E_GAME_STATE_TIME_OUT,//시간 초과
	E_GAME_STATE_END
};